# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-30 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name = 'Page',
            fields = [
                ('id',
                 models.AutoField(auto_created = True, primary_key = True, serialize = False, verbose_name = 'ID')),
                ('title', models.CharField(max_length = 255)),
                ('content', tinymce.models.HTMLField()),
                ('slug', models.CharField(max_length = 255)),
                ('created_at', models.DateTimeField(auto_now_add = True)),
            ],
        ),
    ]
