# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-30 11:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name = 'Age',
            fields = [
                ('id',
                 models.AutoField(auto_created = True, primary_key = True, serialize = False, verbose_name = 'ID')),
                ('name', models.CharField(max_length = 255)),
                ('description', tinymce.models.HTMLField(blank = True)),
                ('created_at', models.DateTimeField(auto_now_add = True)),
            ],
            options = {
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name = 'Poem',
            fields = [
                ('id',
                 models.AutoField(auto_created = True, primary_key = True, serialize = False, verbose_name = 'ID')),
                ('title', models.CharField(max_length = 100)),
                ('content', models.TextField()),
                ('is_shown', models.BooleanField(default = False)),
                ('created_at', models.DateTimeField(auto_now_add = True)),
                ('updated_at', models.DateTimeField(auto_now = True)),
                ('added_user',
                 models.ForeignKey(on_delete = django.db.models.deletion.CASCADE, to = settings.AUTH_USER_MODEL)),
            ],
            options = {
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name = 'Poet',
            fields = [
                ('id',
                 models.AutoField(auto_created = True, primary_key = True, serialize = False, verbose_name = 'ID')),
                ('name', models.CharField(max_length = 255)),
                ('letter', models.CharField(max_length = 5)),
                ('slug', models.SlugField(max_length = 255, unique = True)),
                ('about', tinymce.models.HTMLField(blank = True)),
                ('sex', models.SmallIntegerField(choices = [(1, 'Ер адам'), (2, 'Әйел адам')], default = 1)),
                ('is_active', models.BooleanField(default = False)),
                ('created_at', models.DateTimeField(auto_now_add = True)),
                ('updated_at', models.DateTimeField(auto_now = True)),
                ('age', models.ForeignKey(blank = True, null = True, on_delete = django.db.models.deletion.CASCADE,
                                          to = 'poetry.Age')),
            ],
            options = {
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name = 'Theme',
            fields = [
                ('id',
                 models.AutoField(auto_created = True, primary_key = True, serialize = False, verbose_name = 'ID')),
                ('name', models.CharField(max_length = 255)),
                ('created_at', models.DateTimeField(auto_now_add = True)),
            ],
            options = {
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name = 'View',
            fields = [
                ('id',
                 models.AutoField(auto_created = True, primary_key = True, serialize = False, verbose_name = 'ID')),
                ('views_count', models.IntegerField(default = 0)),
                ('poem', models.ForeignKey(on_delete = django.db.models.deletion.CASCADE, to = 'poetry.Poem')),
            ],
        ),
        migrations.AddField(
            model_name = 'poem',
            name = 'author',
            field = models.ForeignKey(on_delete = django.db.models.deletion.CASCADE, to = 'poetry.Poet'),
        ),
        migrations.AddField(
            model_name = 'poem',
            name = 'theme',
            field = models.ManyToManyField(blank = True, null = True, to = 'poetry.Theme'),
        ),
    ]
