# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-01 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='activation_code',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
