# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-04 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_contributor_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='text_status',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
